version: 2
jobs:
  build:
    docker:
      - image: felicianotech/docker-hugo:latest
    working_directory: ~/project
    steps:
      - checkout

      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              hugo -t introduction
              git config --global user.email "circle@ci.com"
              git config --global user.name "CircleCi"
              git add docs/
              git commit -m "build: [ci skip]"
              git push origin master
            fi